CREATE TABLE [dbo].[Clipboard]
(
	[Id] NCHAR(10) NOT NULL PRIMARY KEY UNIQUE,
	[Order] INT NOT NULL DEFAULT 0,
	[Status] INT NOT NULL DEFAULT 0,
	[DateCompleted] DATE NULL,
	[Title] NVARCHAR(50) NULL,
	[Note] NVARCHAR(MAX) NULL,
	[TimeCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[TimeUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
