CREATE TABLE [dbo].[DayOfCode]
(
	[Id] NCHAR(10) NOT NULL PRIMARY KEY UNIQUE, 
    [Day] INT NOT NULL, 
    [Date] DATE NOT NULL, 
    [Goal] NVARCHAR(150) NULL, 
    [Result] NVARCHAR(150) NULL, 
    [Summary] NVARCHAR(MAX) NULL, 
    [TimeCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), 
    [TimeUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [ViewCount] INT NOT NULL DEFAULT 0
)
