CREATE TABLE [dbo].[Ideas]
(
	[Id] NCHAR(10) NOT NULL PRIMARY KEY UNIQUE,
	[Order] INT NOT NULL DEFAULT 0,
	[Status] INT NOT NULL DEFAULT 0,
	[Title] NVARCHAR(150) NOT NULL,
	[Content] NVARCHAR(MAX) NULL,
	[TimeCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[TimeUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
