CREATE TABLE [dbo].[Links]
(
	[Id] NCHAR(10) NOT NULL PRIMARY KEY UNIQUE, 
	[Order] INT NOT NULL DEFAULT 0,
	[Type] INT NOT NULL DEFAULT 0,
	[Title] NVARCHAR(150) NOT NULL, 
	[URL] NVARCHAR(200) NOT NULL,
	[MenuName] NVARCHAR(50) NOT NULL,
	[Icon] NVARCHAR(100) NOT NULL DEFAULT 'fas fa-link',
	[TimeCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), 
	[TimeUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[IsPublished] BIT NOT NULL DEFAULT 0
)
