CREATE TABLE [dbo].[Page]
(
	[Id] NCHAR(10) NOT NULL PRIMARY KEY UNIQUE, 
	[Order] INT NOT NULL DEFAULT 0,
	[Title] NVARCHAR(150) NOT NULL, 
	[Slug] NVARCHAR(150) NOT NULL,
	[MenuName] NVARCHAR(50) NOT NULL,
	[Icon] NVARCHAR(100) NULL,
	[Content] NVARCHAR(MAX) NOT NULL, 
	[TimeCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), 
	[TimeUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[ViewCount] INT NOT NULL DEFAULT 0,
	[IsPublished] BIT NOT NULL DEFAULT 0
)
