CREATE TABLE [dbo].[Rewind]
(
	[Id] NCHAR(10) NOT NULL PRIMARY KEY UNIQUE, 
	[Date] DATE NOT NULL, 
	[Year] INT NOT NULL DEFAULT 2025,
	[Month] INT NOT NULL DEFAULT 1,
	[Title] NVARCHAR(150) NOT NULL, 
	[Slug] NVARCHAR(150) NOT NULL,
	[Content] NVARCHAR(MAX) NOT NULL, 
	[TimeCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), 
	[TimeUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[ViewCount] INT NOT NULL DEFAULT 0,
	[IsPublished] BIT NOT NULL DEFAULT 0
)