CREATE TABLE [dbo].[Tasks]
(
	[Id] NCHAR(10) NOT NULL PRIMARY KEY UNIQUE, 
	[ProjectId] NCHAR(10) NOT NULL,
	[Order] INT NOT NULL DEFAULT 0,
	[Title] NVARCHAR(50) NULL,
	[Description] NVARCHAR(MAX) NULL,
	[TimeCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[TimeUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
